intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{tinystl}: TINYSTL/hxx{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{tinystl}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into include/TINYSTL/ so consumers keep writing <TINYSTL/vector.h>.
#
TINYSTL/hxx{*}:
{
  install = include/TINYSTL/
}
